// src/app/layout.tsx
import "./globals.css"
import type { Metadata } from "next"
import ClientBody from "./ClientBody"
import Script from "next/script"

export const metadata: Metadata = {
  title: "My Next App",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning className="antialiased">
        {/* External script if needed */}
        <Script
          crossOrigin="anonymous"
          src="//unpkg.com/same-runtime/dist/index.global.js"
        />
        <ClientBody>{children}</ClientBody>
      </body>
    </html>
  )
}
