// src/app/layout.tsx

import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Use a supported font
import "./globals.css";
import ClientBody from "./ClientBody";
import Script from "next/script";

// Load font safely
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.variable}>
      <body suppressHydrationWarning className="antialiased">
        <Script
          crossOrigin="anonymous"
          src="//unpkg.com/same-runtime/dist/index.global.js"
          strategy="beforeInteractive"
        />
        <ClientBody>{children}</ClientBody>
      </body>
    </html>
  );
}