name: Deploy Next.js to GitHub Pages
on: push:
  branches: [main]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3  # set node
        with:
          node-version: 18
      - run: npm ci
      - run: npm run build
      - run: npm run export
      - run: touch out/.nojekyll
      - uses: JamesIves/github-pages-deploy-action@4.4.0
        with:
          branch: gh-pages  # or main/docs
          folder: out
